LNX-83-create-generic-requirements
group-project-gut/lynx-scene-host-python pull request #3
Opened 2023-03-27 21:09 UTC by Krystian030

2023-03-28 16:03 UTC, alpinus4 requested changes

2023-03-28 16:03 UTC, alpinus4 commented on requirements.txt
> +git+https://github.com/group-project-gut/lynx-python-common@LNX-83-create-generic-requirements
It's not specifically a comment to only this PR, but can we just leave it as `master`?

While I understand I'ts not gonna work without the changes in `lynx-python-common`,
we should just keep it as `master` all the time instead of changing it with every commit, and accept it's gonna break things till we merge commit in `lynx-python-common`.

I believe we should first do changes to `lynx-python-common`, then to `scene-host`, etc
and we can keep it as `master` without breaking anything

2023-03-28 16:03 UTC, alpinus4 commented on src/scene_server.py
> +                        return {"error": f"Requirements for {action} are not met"}
While it's okay for debug purposes, otherwise I believe we should just quietly not execute the action and proceed.

2023-03-28 16:46 UTC, blazej-smorawski commented on requirements.txt
> +git+https://github.com/group-project-gut/lynx-python-common@LNX-83-create-generic-requirements
I think it's ok, because we point to a version that works. CI won't pass if we go for master.

2023-03-28 16:48 UTC, blazej-smorawski approved these changes

2023-04-01 11:09 UTC, EasyJB reviewed
Small changes, k

2023-04-16 10:07 UTC, merged