LNX-193 Fix bug with agent delete
group-project-gut/lynx-scene-host-python pull request #30
Opened 2023-09-11 15:21 UTC by Krystian030

2023-09-11 15:23 UTC, filip-szweda requested changes

2023-09-11 15:23 UTC, filip-szweda commented on src/routers/scene_router.py
> +    process_data: ProcessData = state.processes.pop(object_id, None)
Move to `remove_process` helper function

2023-09-11 15:23 UTC, filip-szweda commented on src/routers/scene_router.py
> +    if process_data is not None:
`if process_data:`

2023-09-11 15:23 UTC, filip-szweda commented on src/routers/scene_router.py
> +        process_data.process.terminate()
Consider error handling

2023-09-11 15:23 UTC, filip-szweda commented on src/routers/scene_router.py
>      state.scene.add_to_pending_actions(RemoveObject(object_id).serialize())
Check if the `Object` exists in the map first

2023-09-13 17:42 UTC, EasyJB approved these changes

2023-09-15 22:07 UTC, Krystian030 commented on src/routers/scene_router.py
> +        process_data.process.terminate()
Terminate doesn't raise an excpeption upon invocation.

2023-09-16 10:42 UTC, filip-szweda approved these changes
I've added a few suggestions, but otherwise the change is ready to go :)

2023-09-16 10:42 UTC, filip-szweda commented on src/utils/helper_functions.py
> +    logger.debug(f"Terminating process for object {object_id}")
```suggestion
    logger.debug(f"Terminating process for object with id: {object_id}")
```

2023-09-16 10:42 UTC, filip-szweda commented on src/utils/helper_functions.py
> +def terminate_process_for_object(object_id: int):
```suggestion
def terminate_process_for_object(object_id: int) -> None:
```

2023-09-16 10:42 UTC, filip-szweda commented on src/utils/helper_functions.py
> +    logger.debug(f"Process for object {object_id} has been successfully terminated")
```suggestion
    logger.debug(f"Process has been successfully terminated for object with id: {object_id} ")
```

2023-09-16 10:45 UTC, merged